### ISSUE TITLE
Sampling

### ISSUE THREAD

**Issue by mar-muel** [echen102/COVID-19-TweetIDs#13]
Hi there! Happy to see that you are releasing this data.

Since I'm also collecting/sharing this data (see [here](https://www.crowdbreaks.org/en/data_sharing)) I noticed a while back that unfortunately I'm running into "soft" limits (Twitter caps the volume at 1% of the total stream), so I'm unfortunately missing quite a bit of data (I collect roughly 4M tweets/day currently, probably around a fifth of the total, although it could be higher). 

The problem is that this subsampling might impact certain type of analysis (say counts over time, networks, etc.), see [here](http://users.cecs.anu.edu.au/~siqi.wu/files/icwsm2020sampling.pdf) e.g..

I'm considering merging datasets from different sources in the final analysis (however, granted, it's already a lot of data to process), if I do this I will probably merge various datasets in order to get closer to the full dataset. If I do this, I will of course cite your work.

If you think you face a similar sampling, this is maybe something which could be mentioned in the README as well - especially for others who are not aware of this.

**Comment by emilioferrara** [comment]
Hi Martin, my understanding is that everyone 'listening' into the API receives the same sample and misses out on the same tweets during peak times. It would be interesting if what you say could be done - if you test and see whether our list overlaps with yours (for the same query term) or not, that would be a fine discovery and could lead to enriching datasets from multiple sources.

**Comment by mar-muel** [comment]
Hi Emilio, I wasn't aware you were using the sample API (I thought you used the filter endpoint). This is indeed less of an issue if you use the sample endpoint (since the bias is constant over time).

**Comment by SamSamhuns** [comment]
> Hi Emilio, I wasn't aware you were using the sample API (I thought you used the filter endpoint). This is indeed less of an issue if you use the sample endpoint (since the bias is constant over time).

I do not think they are using the sample API. From [twitter's documentation](https://developer.twitter.com/en/docs/labs/sampled-stream/overview), 

> The sampled stream endpoint allows developers to stream about 1% of all new public Tweets as they happen. 

They are using the filter endpoint with the keywords they mention in the repository and your concerns about the filter API on the counts over time, cascades, and networks are valid based on the paper you mentioned. And this might add biases to certain studies done with this data.

However, everyone does receive the same sample of tweets and misses on the same tweets during peak times as the paper you mentioned the filtered tweet API is deterministic.

**Comment by emilioferrara** [comment]
Sam is correct in both that we are using the filter endpoint (as documented in the paper) and that everyone receives the same sample of tweets because the API algorithm is deterministic. The biases of the filter API have been explored in various papers, most prominently by my lab's member Fred Morstatter. Closing.
