### ISSUE TITLE
Frequency of Updates

### ISSUE THREAD

**Issue by TianSc** [echen102/COVID-19-TweetIDs#14]
Hi there,

How often will the data, tweets be updated and what is the plans for the future of the COVID-19 Tweets

**Comment by debajyotidatta** [comment]
I am also curious about the same question! Hope you all continue to maintain this repository for a long time.

**Comment by echen102** [comment]
Hi, 

The plan is to update IDs on here on a weekly basis (The plan is to update every Monday or latest Tuesday, as my ability to do some initial cleaning - e.g. dropping duplicates and quick data statistics - depends on computational resource availability). I'll be uploading the next batch of tweets tonight (up until 4/3) We'll be continuing to collect tweets and maintaining this repository for the foreseeable future.

**Comment by debajyotidatta** [comment]
That is great! Thanks a lot for the response. Just wanted to know that you all will continue to maintain this repository. There are quite a few repos now, but none of them actively are maintaining it. Glad you guys are maintaining at a weekly frequency.

**Comment by echen102** [comment]
Of course! I've just uploaded the newest batch of data - I'll be closing this issue, but please feel free to let me know if you have any other questions.
