### ISSUE TITLE
Data Absence 

### ISSUE THREAD

**Issue by WangXin-1993** [echen102/COVID-19-TweetIDs#19]
Hi, thanks for sharing this brilliant dataset!

We noticed some issues of the dataset when we process the data.
The Twitter ID files seem absent for some time periods in Feb., including 05-08 at Feb 1, 06 at Feb 8, 21-23 at Feb. 22, the whole day for Feb. 23 and 00-03 at Feb. 24, 00-02 at Feb. 25.

Are there any ways you can fix this issue and complement the data (especially the data on Feb. 23)?

Thanks a lot!

**Comment by emilioferrara** [comment]
Know gaps already discussed in the home page's readme. Closing.
