### ISSUE TITLE
Unexpected higher volume of ids at the end of February

### ISSUE THREAD

**Issue by blas-ko** [echen102/COVID-19-TweetIDs#22]
Hello! 

First of all, many thanks for releasing this great dataset for public use :).

I'm about to start hydrating the data. However, by doing a quick inspection of the sizes of the tweet id txt files, I realized that the tweets from the 29th of February and the 1st of March are abnormally big (~x4 times the average id.txt size). Is this something expected? I want to run some analyses of the COVID conversation in Twitter, so I want to make sure to take all the possible biases into consideration.

On a somewhat unrelated point, I was wondering if using hydrate.py is as fast as using `twarc` from the terminal? If it's not, do you have any ideas of an easy way to scan through all the directories and .txt files directly from the terminal? Maybe with a bash script or so would do the trick...
 
Thanks again!

**Comment by emilioferrara** [comment]
On Feb 29 the first US death was reported and the conversation grows significantly in that period of time, possibly as a consequence of increased attention toward the increasing gravity of the situation in the US. We did not run any test to compare twarc vs hydrate; if you do, please feel free to report your findings here!

**Comment by blas-ko** [comment]
Thanks for the early reply, Emilio! 

I ended up using a very basic bash script (below) that dumps the ids into a single, compressed, csv file.

Both the .py and my bash script hydrate the ids in roughly the same time (tried it for ~5000 ids only).

```shell
#!/bin/bash

# ToDos: 1) Put a progress bar, 2) handle files that have already been processed, 3) resume hydration if paused.

start=`date +%s`

touch "COVID-19-Tweets.csv.gz"

for dir in "2020-01" "2020-02" "2020-03" "2020-04" "2020-05"
do
 
 for file in "$dir"/coronavirus*.txt
 do

  lines=$(wc -l < "$file")
  echo "Processing $file with $lines ids."

  twarc --format csv hydrate "$file" | gzip - >> "COVID-19-Tweets.csv.gz"


 done

done

end=`date +%s`

echo "Done! Execution time was `expr $end - $start` seconds."
```

**Comment by emilioferrara** [comment]
Good to know and thanks for the test. Users will find it useful to know that the two approaches are comparable. Thanks.
