### ISSUE TITLE
inquiry for the missing files from 2020-02-01-04 to 2020-02-01-08 (five files)

### ISSUE THREAD

**Issue by WonKim-Stat** [echen102/COVID-19-TweetIDs#24]
Hello! I was wondering if there are those five files available? I hydrated the data and found that there are five files missed in February section. Thank you in advance for your support!

**Comment by WonKim-Stat** [comment]
Also, 2020-02-08-06?..

**Comment by echen102** [comment]
Hi @WonKim-Stat , please see the "Known Gaps" section in the Readme for a list of missing hours in our data set. Closing this issue for now as these are known gaps
