### ISSUE TITLE
derived analysis

### ISSUE THREAD

**Issue by WeileiZeng** [echen102/COVID-19-TweetIDs#26]
I am teaching some high school student on data science, and think this is a good sample project. Is there a list of report or analysis coming out from these data?

I saw the initial post on arxiv, and I am wondering if people have done more after march. Thanks!

**Comment by echen102** [comment]
Hi! Thanks for reaching out.

We do have an updated version of the initial arxiv paper : [Tracking Social Media Discourse About the COVID-19 Pandemic: Development of a Public Coronavirus Twitter Data Set](https://publichealth.jmir.org/2020/2/e19273/)

We also recently published the following paper, which also leverages our collected data : [Political polarization drives online conversations about COVID ‐19 in the United States](https://publons.com/publon/10.1002/hbe2.202/)

Other folks in the research community have also used our data set (after hydrating) and have[ cited our paper ](https://scholar.google.com/scholar?oi=bibs&hl=en&cites=17247205926594590834,7567503903529083679&as_sdt=5). 

Hope this helps & please let me know if you have any other questions!

**Comment by WeileiZeng** [comment]
Thanks!
