### ISSUE TITLE
Program to get the full dataset

### ISSUE THREAD

**Issue by Gautamshahi** [echen102/COVID-19-TweetIDs#27]
Hello,

Can you please suggest any program/open-source code which allows crawling a large number of tweets from TweetId?

I have a written a python script but it's not smart enough to handle millions of tweet id.

**Comment by echen102** [comment]
Hi @Gautamshahi , 

Unfortunately we are all limited by Twitter's policies and rate limiting when it comes to rehydrating tweets from their tweet-ids. Our community has contributed a script that has been committed to this repo that will rehydrate the tweets and manage the rate limiting for you.
