### ISSUE TITLE
twarc configure and hydrate issue

### ISSUE THREAD

**Issue by gklabs** [echen102/COVID-19-TweetIDs#28]
I ran `twarc configure` and entered the consumer and API keys that it asks for. Yet when executing `python3 hydrate.py` the following error throws up
![image](https://user-images.githubusercontent.com/18333582/90836813-61597c80-e31e-11ea-83cb-30ff8fbeecb3.png)

**Comment by echen102** [comment]
Hi @gklabs if you don't have any other issues, I'm going to go ahead and close this. Please feel free to reach out if you run into any issues. If Twarc isn't working, you might want to try DocNow's [Hydrator](https://github.com/DocNow/hydrator) which provides a GUI where you can configure settings and check to see if it's an issue with your tokens and keys.

**Comment by gklabs** [comment]
Thank you, I used the Hydrator to get the tweets.
