### ISSUE TITLE
Feb 23 Data 

### ISSUE THREAD

**Issue by ngathan** [echen102/COVID-19-TweetIDs#30]
Hi, 

Thanks so much for making the data available. I am trying to write a paper that uses your amazing dataset. However, when I was doing exploratory data analysis, I found that data for Feb 23, 2020 are missing. Is there any way to recover that data? 

Appreciatively, 

Nga Than

**Comment by echen102** [comment]
Hi, 
Unfortunately no - all of these Tweets were collected in real time and we had some major technical issues during those days. All missing times are listed in the README, and have been addressed in previous issues that were opened.

**Comment by echen102** [comment]
Closing this issue as these gaps are known and listed in the README. Please feel free to reach out if you still have questions!
