### ISSUE TITLE
Sensitive data in tweets

### ISSUE THREAD

**Issue by rmunro** [echen102/COVID-19-TweetIDs#33]
I just saw a paper rejected from a conference on ethical grounds that used this dataset.

I appreciate that you ask people to abide by Twitter's terms of service as a condition of using this dataset. However, people don't seem to be reading it. In particular, Twitter terms forbid the encoding of sensitive data including people's health. This would include someone's COVID-19 status (even if negative) and their exposure. Twitter also permits children as young as 13 to use the platform, who are not legally capable of giving their consent for some use cases, including health-related cases, in many countries. 

So, I recommend that you add a more explicit warning that this is very sensitive data.

**Comment by emiliofe** [comment]
Hi Rob. Thanks for your comment. This is just a dataset of tweet IDs. There is no content so there are no risks associated with the type of problems you described in association with just the tweet IDs. Any dataset’s user has to abide to the rules that Twitter sets, if they choose to rehydrate our dataset to get the content. Also, obviously, everyone should abide to the IRB regulations that apply. We have already a disclaimer for that but I guess reiterating isn’t a bad idea. I’ll close this. Thanks
