### ISSUE TITLE
How to hydrate only 1% of all tweet ids

### ISSUE THREAD

**Issue by kennethlee33** [echen102/COVID-19-TweetIDs#34]
Hi there, because of the rate limiting I was wondering how I can randomly hydrate 1% of all tweet ids from the text files. Currently I use a random number generator and my JSON files contains 1% of hydrated tweets, however in the hydrate.py code "twarc.hydrate()" still passes in every id because it accepts the text file as a whole and so rate limiting still occurs at the normal rate. Is there a way to modify the code or all text files so that I only hydrate 1% of all tweets?

**Comment by cristophersfr** [comment]
Hi @kennethlee33 !! I had the same issue as you, and for this, I wrote a script to sample 1% of all tweet IDs in the .txt files. 

Here it is:
```python
#!/usr/bin/env python3
"""
This script walks through the dataset repos and randomly select 1% of the Tweet IDs.
"""

import math
import random

from pathlib import Path

random.seed(43)

REP = 'COVID-19-TweetIDs/'

data_dirs = ['2020-01', '2020-02', '2020-03', '2020-04', '2020-05', '2020-06', '2020-07', '2020-08', '2020-09', '2020-10', '2020-11', '2020-12', '2021-01']


def main():
    for data_dir in data_dirs:
        for path in Path(REP + data_dir).iterdir():
            if path.name.endswith('.txt'):
                sample(path)


def sample(id_file):
    print('samling {}'.format(id_file))

    # Sampling the files
    with open(id_file) as file:
        lines = file.read().splitlines()

    n_lines = math.ceil(len(lines) * 0.01)
    print(n_lines)

    random_lines = random.sample(lines, n_lines)

    with open(id_file, 'w') as output_file:
        output_file.writelines(line + "\n"
                               for line in random_lines)

if __name__ == "__main__":
    main()
```

**Comment by kennethlee33** [comment]
Hi @cristophersfr , I just tried using your code to reduce the .txt files down to 1/100th of the original lines and it worked! Thank you very much for your help, I appreciate it!
