### ISSUE TITLE
I want to know the number of Korean tweets.

### ISSUE THREAD

**Issue by jangscon** [echen102/COVID-19-TweetIDs#42]
First of all, thank you for organizing a good dataset. I have a question. Only Language breakdown of top 15 most prestigious languages are written in README, and the share of Korean is not stated. There is too much data for me to count Korean tweets. Can I know the share of Korean?

**Comment by echen102** [comment]
Hi! Not sure if you still need the number, but for release v2.102, there are 2,166,786 Korean tweets across our entire dataset. A quick note that these are tweets that Twitter has automatically detected are written in Korean.
