### ISSUE TITLE
geolocations missing

### ISSUE THREAD

**Issue by thu07** [echen102/COVID-19-TweetIDs#6]
First of all, thank you so much for sharing your work.

I run the script and get some tweets full content. However, I found all the geolocations are missing, even though some users' "geo_enable = true". My question is if there's a way that I can get the geolocation information.

Thanks again!

**Comment by echen102** [comment]
Hi @thu07 , you're quite welcome! 

W.r.t. the geolocations, we did a quick search through a subset of our collected Tweets and found that very few Tweets contain location metadata (in particular the place or coordinates objects). Twitter recently [changed](https://twitter.com/TwitterSupport/status/1141039841993355264) the way they collect location data, which severely reduced the Tweets that have location data attached in the first place. 

Unfortunately, I don't believe that there is a way to retrieve location information that isn't in the returned payload.

**Comment by thu07** [comment]
Thank you,@echen102.

So, how about country-level location? Do you have any suggestions?

**Comment by kbathina** [comment]
The user profile has a location field. I think this is user inputted, so there is no guarantee about its accuracy. You can also try the language field as a secondary option

**Comment by echen102** [comment]
The user specified location may be your best bet to identify the country. But as @kbathina  mentioned, this is user specified, so locations can be whatever the user wants it to be (for example, some might have "Hogwarts" or "middle of the ocean" listed as their location). You can try to filter out for those that have a real location - but depending on whether or not a user regularly updates his/her location, you may or may not get an accurate current location and it may not be representative of where they're currently tweeting from.

**Comment by echen102** [comment]
Hi @thu07 , I'm going to go ahead and close this issue - please feel free to let me know if you have any other issues!
