### ISSUE TITLE
full context is truncated 

### ISSUE THREAD

**Issue by LiyuanLucasLiu** [echen102/COVID-19-TweetIDs#7]
Thanks for sharing!
I've successfully hydrated all tweets with Twarc. However, I the full texts of re-tweets are truncated. For example, the hydrated full-text for a retweet is:
```
 'full_text': 'RT @ianjamesyoung70: I have noticed a tendency among Vancouverites of the non-Asian persuasion to snicker at face masks viz the risks posed…
```
At the same time, the full context is:
```
I have noticed a tendency among Vancouverites of the non-Asian persuasion to snicker at face masks viz the risks posed by the Wuhan coronavirus. I don't laugh. People who were in Hong Kong during the 2002-2003 Sars outbreak don't laugh. It was a shared trauma for millions 2/
```

Wondering whether it is possible to retrieve the full-text for those retweets. 

Thanks in advance.

**Comment by LiyuanLucasLiu** [comment]
found the full-context in another field of meta-data.

**Comment by echen102** [comment]
Hi @LiyuanLucasLiu - I'm glad you found the full text in the rest of the metadata! I'm actually going to remove this issue because it contains full text from a Tweet
