### ISSUE TITLE
Open Source Helps!

### ISSUE THREAD

**Issue by WeileiZeng** [echen102/COVID-19-TweetIDs#8]
Thanks for your work to help the people in need! Your site has been added! I currently maintain the Open-Source-COVID-19 page, which collects all open source projects related to COVID-19, including maps, data, news, api, analysis, medical and supply information, etc. Please share to anyone who might need the information in the list, or will possibly contribute to some of those projects. You are also welcome to recommend more projects.

http://open-source-covid-19.weileizeng.com/

Cheers!

**Comment by WeileiZeng** [comment]
I understand that the texts of tweets are not allowed to share. But are you going to publish more analysis result, like keyword daily frequency, or word cloud, etc. Or share a list of other projects using those data to do further analysis?

**Comment by echen102** [comment]
Hi @WeileiZeng , thanks for adding our repository to your website! We actually have published an [article on Medium](https://medium.com/@jabawack/twitter-covid-19-preliminary-geo-analysis-ab755eafc88f) on an initial geo-analysis using the Twitter data, in addition to our [initial post](https://medium.com/@jabawack/twitter-dataset-related-to-covid-19-coronavirus-released-cd0b8472d2d0) about the dataset. We hope to release more posts and analysis in the future and we will keep this page updated with anything new!

**Comment by echen102** [comment]
Hi @WeileiZeng, I'm going to go ahead and close this issue, but please feel free to let me know if you have any other issues!

**Comment by WeileiZeng** [comment]
sounds good!

You may have noticed but here is similar project
https://github.com/thepanacealab/covid19_twitter
