### ISSUE TITLE
Updates dataset

### ISSUE THREAD

**Issue by pbvahlst** [echen102/COVID-19-TweetIDs#9]
Thank you very much this repo 😊. Will you update with the latest ids for march at som point?

**Comment by echen102** [comment]
Hi @pbvahlst , you are quite welcome! 

I am trying to establish a more regular pipeline to get these Tweets out in a timely manner (still ironing out some hiccups) , and hope to have new data (through March 20) uploaded sometime today or tomorrow.

**Comment by pbvahlst** [comment]
Very much appreciated. Thanks.
